# Generated by Django 4.2.16 on 2024-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_details_servicerequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/service_requests'),
        ),
    ]
