# Generated by Django 4.2.16 on 2024-11-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_servicerequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/'),
        ),
    ]
